
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//		File name:		Resource2.h
//		Description:	User-definition resource IDs
//		Owner:			AnthonyLeeStark
//		
//		History:		<1> 2024.01.27:		Create new
//						<2> 2024.07.06:		Update to version 3.1
//						<3> 2024.12.18:		Update to version 3.2
//
//		Copyright (c) 2015-2024 AnthonyLeeStark
//
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#pragma once


//////////////////////////////////////////////////////////////////////////
// 
// Define macros using for language table package info
// 
//////////////////////////////////////////////////////////////////////////

#define LANGPACKINFO_LANGPACKID									0x0c0001
#define LANGPACKINFO_LANGNAMEID									0x0c0002
#define LANGPACKINFO_LANGNAMEFULL								0x0c0003
#define LANGPACKINFO_DESCRIPTIONID								0x0c0004
#define LANGPACKINFO_DESCRIPTIONFULL							0x0c0005


//////////////////////////////////////////////////////////////////////////
// 
//	Define user-define resource ID groups
//
//////////////////////////////////////////////////////////////////////////

#define RESOURCEID_BUTTON										0x0c1000
#define RESOURCEID_GRIDCOLUMN									0x0c2000
#define RESOURCEID_FORMATSTRING									0x0c3000
#define RESOURCEID_ACTIONNAME									0x0c4000
#define RESOURCEID_MESSAGE										0x0c5000
#define RESOURCEID_COMBOSELECTION								0x0c6000
#define RESOURCEID_NOTIFYTIP									0x0c7000
#define RESOURCEID_BALLOONTIP									0x0c8000
#define RESOURCEID_MESSAGEBOX									0x0c9000
#define RESOURCEID_SPECIAL										0x0ca000


//////////////////////////////////////////////////////////////////////////
// 
//	Define user-define resource IDs
//
//////////////////////////////////////////////////////////////////////////

#define BTN_HELPDLG_VIEWMODE_HELPFILE							(RESOURCEID_BUTTON+1)
#define BTN_HELPDLG_VIEWMODE_CHANGELOG							(RESOURCEID_BUTTON+2)
#define BTN_SCHEDULEDLG_SAVECHANGES								(RESOURCEID_BUTTON+3)
#define BTN_SCHEDULEDLG_CANCELCHANGES							(RESOURCEID_BUTTON+4)
#define BTN_HKSETDLG_ADD_MODEADD								(RESOURCEID_BUTTON+5)
#define BTN_HKSETDLG_ADD_MODEUPDATE								(RESOURCEID_BUTTON+6)
#define BTN_HKSETDLG_CHECKALL									(RESOURCEID_BUTTON+7)
#define BTN_HKSETDLG_UNCHECKALL									(RESOURCEID_BUTTON+8)
#define BTN_PWRRMDDLG_SAVECHANGES								(RESOURCEID_BUTTON+9)

//////////////////////////////////////////////////////////////////////////

#define GRIDCOLUMN_LOGVIEWER_DATETIME							(RESOURCEID_GRIDCOLUMN+1)
#define GRIDCOLUMN_LOGVIEWER_CATEGORY							(RESOURCEID_GRIDCOLUMN+2)
#define GRIDCOLUMN_LOGVIEWER_DESCRIPTION						(RESOURCEID_GRIDCOLUMN+3)
#define GRIDCOLUMN_MULTISCHEDULE_INDEX							(RESOURCEID_GRIDCOLUMN+4)
#define GRIDCOLUMN_MULTISCHEDULE_STATE							(RESOURCEID_GRIDCOLUMN+5)
#define GRIDCOLUMN_MULTISCHEDULE_ACTIONID						(RESOURCEID_GRIDCOLUMN+6)
#define GRIDCOLUMN_MULTISCHEDULE_TIMEVALUE						(RESOURCEID_GRIDCOLUMN+7)
#define GRIDCOLUMN_MULTISCHEDULE_TIMEFORMAT						(RESOURCEID_GRIDCOLUMN+8)
#define GRIDCOLUMN_MULTISCHEDULE_REPEAT							(RESOURCEID_GRIDCOLUMN+9)
#define GRIDCOLUMN_HOTKEYSET_STATE								(RESOURCEID_GRIDCOLUMN+10)
#define GRIDCOLUMN_HOTKEYSET_HKACTIONID							(RESOURCEID_GRIDCOLUMN+11)
#define GRIDCOLUMN_HOTKEYSET_KEYSTROKES							(RESOURCEID_GRIDCOLUMN+12)
#define GRIDCOLUMN_PWRREMINDER_INDEX							(RESOURCEID_GRIDCOLUMN+13)
#define GRIDCOLUMN_PWRREMINDER_STATE							(RESOURCEID_GRIDCOLUMN+14)
#define GRIDCOLUMN_PWRREMINDER_ITEMID							(RESOURCEID_GRIDCOLUMN+15)
#define GRIDCOLUMN_PWRREMINDER_MESSAGE							(RESOURCEID_GRIDCOLUMN+16)
#define GRIDCOLUMN_PWRREMINDER_EVENTID							(RESOURCEID_GRIDCOLUMN+17)
#define GRIDCOLUMN_PWRREMINDER_STYLE							(RESOURCEID_GRIDCOLUMN+18)
#define GRIDCOLUMN_PWRREMINDER_REPEAT							(RESOURCEID_GRIDCOLUMN+19)

//////////////////////////////////////////////////////////////////////////

#define FORMAT_TIMEPERIOD_ANTE_MERIDIEM							(RESOURCEID_FORMATSTRING+1)
#define FORMAT_TIMEPERIOD_POST_MERIDIEM							(RESOURCEID_FORMATSTRING+2)

//////////////////////////////////////////////////////////////////////////

#define ACTION_NAME_NOTHING										(RESOURCEID_ACTIONNAME+1)
#define ACTION_NAME_DISPLAYOFF									(RESOURCEID_ACTIONNAME+2)
#define ACTION_NAME_SLEEP										(RESOURCEID_ACTIONNAME+3)
#define ACTION_NAME_SHUTDOWN									(RESOURCEID_ACTIONNAME+4)
#define ACTION_NAME_RESTART										(RESOURCEID_ACTIONNAME+5)
#define ACTION_NAME_SIGNOUT										(RESOURCEID_ACTIONNAME+6)
#define ACTION_NAME_HIBERNATE									(RESOURCEID_ACTIONNAME+7)
#define ACTION_NAME_SHOWMENU									(RESOURCEID_ACTIONNAME+8)

//////////////////////////////////////////////////////////////////////////

#define MESSAGE_ACTION_DISPLAYOFF								(RESOURCEID_MESSAGE+1)
#define MESSAGE_ACTION_SLEEP									(RESOURCEID_MESSAGE+2)
#define MESSAGE_ACTION_SHUTDOWN									(RESOURCEID_MESSAGE+3)
#define MESSAGE_ACTION_RESTART									(RESOURCEID_MESSAGE+4)
#define MESSAGE_ACTION_SIGNOUT									(RESOURCEID_MESSAGE+5)
#define MESSAGE_ACTION_HIBERNATE								(RESOURCEID_MESSAGE+6)
#define MESSAGE_SCHEDNOTIFY_DISPLAYOFF							(RESOURCEID_MESSAGE+7)
#define MESSAGE_SCHEDNOTIFY_SLEEP								(RESOURCEID_MESSAGE+8)
#define MESSAGE_SCHEDNOTIFY_SHUTDOWN							(RESOURCEID_MESSAGE+9)
#define MESSAGE_SCHEDNOTIFY_RESTART								(RESOURCEID_MESSAGE+10)
#define MESSAGE_SCHEDNOTIFY_SIGNOUT								(RESOURCEID_MESSAGE+11)
#define MESSAGE_SCHEDNOTIFY_HIBERNATE							(RESOURCEID_MESSAGE+12)

//////////////////////////////////////////////////////////////////////////

#define COMBOBOX_ACTION_DISPLAYOFF								(RESOURCEID_COMBOSELECTION+1)
#define COMBOBOX_ACTION_SLEEP									(RESOURCEID_COMBOSELECTION+2)
#define COMBOBOX_ACTION_SHUTDOWN								(RESOURCEID_COMBOSELECTION+3)
#define COMBOBOX_ACTION_RESTART									(RESOURCEID_COMBOSELECTION+4)
#define COMBOBOX_ACTION_SIGNOUT									(RESOURCEID_COMBOSELECTION+5)
#define COMBOBOX_ACTION_HIBERNATE								(RESOURCEID_COMBOSELECTION+6)
#define COMBOBOX_ACTION_SHOWMENU								(RESOURCEID_COMBOSELECTION+7)
#define COMBOBOX_LANGUAGE_ENGLISH								(RESOURCEID_COMBOSELECTION+8)
#define COMBOBOX_LANGUAGE_VIETNAMESE							(RESOURCEID_COMBOSELECTION+9)
#define COMBOBOX_LANGUAGE_SIMPCHINESE							(RESOURCEID_COMBOSELECTION+10)
#define COMBOBOX_MSGSTYLE_MESSAGEBOX							(RESOURCEID_COMBOSELECTION+11)
#define COMBOBOX_MSGSTYLE_DIALOGBOX								(RESOURCEID_COMBOSELECTION+12)

//////////////////////////////////////////////////////////////////////////

#define NOTIFY_TIP_TEMPLATE										(RESOURCEID_NOTIFYTIP+1)
#define NOTIFY_TIP_DISPLAYOFF									(RESOURCEID_NOTIFYTIP+2)
#define NOTIFY_TIP_SLEEP										(RESOURCEID_NOTIFYTIP+3)
#define NOTIFY_TIP_SHUTDOWN										(RESOURCEID_NOTIFYTIP+4)
#define NOTIFY_TIP_RESTART										(RESOURCEID_NOTIFYTIP+5)
#define NOTIFY_TIP_SIGNOUT										(RESOURCEID_NOTIFYTIP+6)
#define NOTIFY_TIP_HIBERNATE									(RESOURCEID_NOTIFYTIP+7)
#define NOTIFY_TIP_SHOWMENU										(RESOURCEID_NOTIFYTIP+8)

//////////////////////////////////////////////////////////////////////////

#define BALLOON_TIP_TEMPLATE									(RESOURCEID_BALLOONTIP+1)
#define BALLOON_TIP_DISPLAYOFF									(RESOURCEID_BALLOONTIP+2)
#define BALLOON_TIP_SLEEP										(RESOURCEID_BALLOONTIP+3)
#define BALLOON_TIP_SHUTDOWN									(RESOURCEID_BALLOONTIP+4)
#define BALLOON_TIP_RESTART										(RESOURCEID_BALLOONTIP+5)
#define BALLOON_TIP_SIGNOUT										(RESOURCEID_BALLOONTIP+6)
#define BALLOON_TIP_HIBERNATE									(RESOURCEID_BALLOONTIP+7)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_CONFIG_NONE										(RESOURCEID_MESSAGEBOX+100)
#define MSGBOX_CONFIG_RELOAD_CAPTION							(MSGBOX_CONFIG_NONE+1)
#define MSGBOX_CONFIG_CHANGED_CONTENT							(MSGBOX_CONFIG_NONE+2)
#define MSGBOX_CONFIG_NOTCHANGED_CONTENT						(MSGBOX_CONFIG_NONE+3)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_EDITSCHEDULE_NONE								(RESOURCEID_MESSAGEBOX+200)
#define MSGBOX_EDITSCHEDULE_CAPTION								(MSGBOX_EDITSCHEDULE_NONE+1)
#define MSGBOX_EDITSCHEDULE_CHANGED_CAPTION						(MSGBOX_EDITSCHEDULE_NONE+2)
#define MSGBOX_EDITSCHEDULE_CHANGED_CONTENT						(MSGBOX_EDITSCHEDULE_NONE+3)
#define MSGBOX_MULTISCHEDULE_CAPTION							(MSGBOX_EDITSCHEDULE_NONE+4)
#define MSGBOX_MULTISCHEDULE_CHANGED_CAPTION					(MSGBOX_EDITSCHEDULE_NONE+5)
#define MSGBOX_MULTISCHEDULE_CHANGED_CONTENT					(MSGBOX_EDITSCHEDULE_NONE+6)
#define MSGBOX_MULTISCHEDULE_REMOVE_ITEM						(MSGBOX_EDITSCHEDULE_NONE+7)
#define MSGBOX_MULTISCHEDULE_REMOVEALL_ITEMS					(MSGBOX_EDITSCHEDULE_NONE+8)
#define MSGBOX_MULTISCHEDULE_NOTREMOVE_DEFAULT					(MSGBOX_EDITSCHEDULE_NONE+9)
#define MSGBOX_MULTISCHEDULE_CONFIRM_SETDEFAULT					(MSGBOX_EDITSCHEDULE_NONE+10)
#define MSGBOX_MULTISCHEDULE_CONFIRM_EXITMODE					(MSGBOX_EDITSCHEDULE_NONE+11)
#define MSGBOX_EDITSCHEDULE_INVALIDITEM_ITEMID					(MSGBOX_EDITSCHEDULE_NONE+12)
#define MSGBOX_EDITSCHEDULE_INVALIDITEM_ACTIONID				(MSGBOX_EDITSCHEDULE_NONE+13)
#define MSGBOX_EDITSCHEDULE_INVALIDITEM_TIMEVALUE				(MSGBOX_EDITSCHEDULE_NONE+14)
#define MSGBOX_EDITSCHEDULE_INVALIDITEM_SNOOZEINTERVAL			(MSGBOX_EDITSCHEDULE_NONE+15)
#define MSGBOX_EDITSCHEDULE_INVALIDITEM_ACTIVEDAYS				(MSGBOX_EDITSCHEDULE_NONE+16)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_MULTISCHEDULE_NONE								(RESOURCEID_MESSAGEBOX+300)
#define MSGBOX_MULTISCHEDULE_INVALIDITEM_ITEMID					(MSGBOX_MULTISCHEDULE_NONE+1)
#define MSGBOX_MULTISCHEDULE_INVALIDITEM_ACTIONID				(MSGBOX_MULTISCHEDULE_NONE+2)
#define MSGBOX_MULTISCHEDULE_INVALIDITEM_TIMEVALUE				(MSGBOX_MULTISCHEDULE_NONE+3)
#define MSGBOX_MULTISCHEDULE_INVALIDITEM_TIMEDUPLICATE			(MSGBOX_MULTISCHEDULE_NONE+4)
#define MSGBOX_MULTISCHEDULE_INVALIDITEM_SNOOZEINTERVAL			(MSGBOX_MULTISCHEDULE_NONE+5)
#define MSGBOX_MULTISCHEDULE_INVALIDITEM_ACTIVEDAYS				(MSGBOX_MULTISCHEDULE_NONE+6)
#define MSGBOX_MULTISCHEDULE_INVALIDITEM_AUTOCORRECT			(MSGBOX_MULTISCHEDULE_NONE+7)
#define MSGBOX_MULTISCHEDULE_UPDATEERROR_SUCCESS				(MSGBOX_MULTISCHEDULE_NONE+8)
#define MSGBOX_MULTISCHEDULE_UPDATEERROR_ISDEFAULT				(MSGBOX_MULTISCHEDULE_NONE+9)
#define MSGBOX_MULTISCHEDULE_UPDATEERROR_EMPTY					(MSGBOX_MULTISCHEDULE_NONE+10)
#define MSGBOX_MULTISCHEDULE_UPDATEERROR_MAXITEM				(MSGBOX_MULTISCHEDULE_NONE+11)
#define MSGBOX_MULTISCHEDULE_UPDATEERROR_DUPLICATE				(MSGBOX_MULTISCHEDULE_NONE+12)
#define MSGBOX_MULTISCHEDULE_UPDATEERROR_DUPLICATETIME			(MSGBOX_MULTISCHEDULE_NONE+13)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_PROCESSSCHEDULE_NONE								(RESOURCEID_MESSAGEBOX+400)
#define MSGBOX_PROCESSSCHEDULE_NOTIFY							(MSGBOX_PROCESSSCHEDULE_NONE+1)
#define MSGBOX_PROCESSSCHEDULE_ALLOWCANCEL						(MSGBOX_PROCESSSCHEDULE_NONE+2)
#define MSGBOX_PROCESSSCHEDULE_CANCELED							(MSGBOX_PROCESSSCHEDULE_NONE+3)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_HOTKEYSET_NONE									(RESOURCEID_MESSAGEBOX+500)
#define MSGBOX_HOTKEYSET_CAPTION								(MSGBOX_HOTKEYSET_NONE+1)
#define MSGBOX_HOTKEYSET_REG_FAILED								(MSGBOX_HOTKEYSET_NONE+2)
#define MSGBOX_HOTKEYSET_UNREG_FAILED							(MSGBOX_HOTKEYSET_NONE+3)
#define MSGBOX_HOTKEYSET_CHANGED_CONTENT						(MSGBOX_HOTKEYSET_NONE+4)
#define MSGBOX_HOTKEYSET_REMOVE_ITEM							(MSGBOX_HOTKEYSET_NONE+5)
#define MSGBOX_HOTKEYSET_REMOVEALL_ITEMS						(MSGBOX_HOTKEYSET_NONE+6)
#define MSGBOX_HOTKEYSET_INVALIDITEM_ACTIONID					(MSGBOX_HOTKEYSET_NONE+7)
#define MSGBOX_HOTKEYSET_INVALIDITEM_CTRLKEY					(MSGBOX_HOTKEYSET_NONE+8)
#define MSGBOX_HOTKEYSET_INVALIDITEM_FUNCKEY					(MSGBOX_HOTKEYSET_NONE+9)
#define MSGBOX_HOTKEYSET_INVALIDITEM_EMPTY						(MSGBOX_HOTKEYSET_NONE+10)
#define MSGBOX_HOTKEYSET_EXISTED_HOTKEY							(MSGBOX_HOTKEYSET_NONE+11)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_PWRREMINDER_NONE									(RESOURCEID_MESSAGEBOX+600)
#define MSGBOX_PWRREMINDER_CAPTION								(MSGBOX_PWRREMINDER_NONE+1)
#define MSGBOX_PWRREMINDER_DISPLAY_FAILED						(MSGBOX_PWRREMINDER_NONE+2)
#define MSGBOX_PWRREMINDER_UPDATE_FAILED						(MSGBOX_PWRREMINDER_NONE+3)
#define MSGBOX_PWRREMINDER_CHANGED_CONTENT						(MSGBOX_PWRREMINDER_NONE+4)
#define MSGBOX_PWRREMINDER_REMOVE_ITEM							(MSGBOX_PWRREMINDER_NONE+5)
#define MSGBOX_PWRREMINDER_REMOVEALL_ITEMS						(MSGBOX_PWRREMINDER_NONE+6)
#define MSGBOX_PWRREMINDER_CONFIRM_EXITMODE						(MSGBOX_PWRREMINDER_NONE+7)
#define MSGBOX_PWRREMINDER_INVALIDITEM_ITEMID					(MSGBOX_PWRREMINDER_NONE+8)
#define MSGBOX_PWRREMINDER_INVALIDITEM_MESSAGE_EMPTY			(MSGBOX_PWRREMINDER_NONE+9)
#define MSGBOX_PWRREMINDER_INVALIDITEM_MESSAGE_OUTOFLIMIT		(MSGBOX_PWRREMINDER_NONE+10)
#define MSGBOX_PWRREMINDER_INVALIDITEM_MESSAGE_INVALIDCHAR		(MSGBOX_PWRREMINDER_NONE+11)
#define MSGBOX_PWRREMINDER_INVALIDITEM_EVENTID					(MSGBOX_PWRREMINDER_NONE+12)
#define MSGBOX_PWRREMINDER_INVALIDITEM_TIMEVALUE				(MSGBOX_PWRREMINDER_NONE+13)
#define MSGBOX_PWRREMINDER_INVALIDITEM_STYLEID					(MSGBOX_PWRREMINDER_NONE+14)
#define MSGBOX_PWRREMINDER_INVALIDITEM_SNOOZEINTERVAL			(MSGBOX_PWRREMINDER_NONE+15)
#define MSGBOX_PWRREMINDER_INVALIDITEM_ACTIVEDAYS				(MSGBOX_PWRREMINDER_NONE+16)
#define MSGBOX_PWRREMINDER_INVALIDITEM_AUTOCORRECT				(MSGBOX_PWRREMINDER_NONE+17)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_LOGVIEWER_NONE									(RESOURCEID_MESSAGEBOX+700)
#define MSGBOX_LOGVIEWER_CAPTION								(MSGBOX_LOGVIEWER_NONE+1)
#define MSGBOX_LOGVIEWER_CONFIRM_REMOVEALLRECORDS				(MSGBOX_LOGVIEWER_NONE+2)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_OTHER_NONE										(RESOURCEID_MESSAGEBOX+800)
#define MSGBOX_OTHER_NOTRUNASADMIN								(MSGBOX_OTHER_NONE+1)
#define MSGBOX_OTHER_REQUEST_RESTARTASADMIN						(MSGBOX_OTHER_NONE+2)
#define MSGBOX_OTHER_RUNASADMIN_NEXTTIME						(MSGBOX_OTHER_NONE+3)
#define MSGBOX_OTHER_ALREADY_ADMIN								(MSGBOX_OTHER_NONE+4)
#define MSGBOX_OTHER_FUNCTION_NOT_AVAILABLE						(MSGBOX_OTHER_NONE+5)
#define MSGBOX_OTHER_PREDESTROY_REMINDERDISP					(MSGBOX_OTHER_NONE+6)

//////////////////////////////////////////////////////////////////////////

#define MSGBOX_ERROR_NONE										(RESOURCEID_MESSAGEBOX+900)
#define MSGBOX_ERROR_CAPTION									(MSGBOX_ERROR_NONE+1)
#define MSGBOX_ERROR_SUCCESS									(MSGBOX_ERROR_NONE+2)
#define MSGBOX_ERROR_FAILED										(MSGBOX_ERROR_NONE+3)
#define MSGBOX_ERROR_WRONG_ARGUMENT								(MSGBOX_ERROR_NONE+4)
#define MSGBOX_ERROR_INVALID_FUNCTION							(MSGBOX_ERROR_NONE+5)
#define MSGBOX_ERROR_FILE_NOT_FOUND								(MSGBOX_ERROR_NONE+6)
#define MSGBOX_ERROR_PATH_NOT_FOUND								(MSGBOX_ERROR_NONE+7)
#define MSGBOX_ERROR_ACCESS_DENIED								(MSGBOX_ERROR_NONE+8)
#define MSGBOX_ERROR_INVALID_HANDLE								(MSGBOX_ERROR_NONE+9)
#define MSGBOX_ERROR_INVALID_DATA								(MSGBOX_ERROR_NONE+10)
#define MSGBOX_ERROR_NO_MORE_FILES								(MSGBOX_ERROR_NONE+11)
#define MSGBOX_ERROR_FILE_EXISTS								(MSGBOX_ERROR_NONE+12)
#define MSGBOX_ERROR_CANNOT_MAKE								(MSGBOX_ERROR_NONE+13)
#define MSGBOX_ERROR_INVALID_PARAMETER							(MSGBOX_ERROR_NONE+14)
#define MSGBOX_ERROR_OPEN_FAILED								(MSGBOX_ERROR_NONE+15)
#define MSGBOX_ERROR_BUFFER_OVERFLOW							(MSGBOX_ERROR_NONE+16)
#define MSGBOX_ERROR_INVALID_NAME								(MSGBOX_ERROR_NONE+17)
#define MSGBOX_ERROR_DIR_NOT_EMPTY								(MSGBOX_ERROR_NONE+18)
#define MSGBOX_ERROR_FAIL_SHUTDOWN								(MSGBOX_ERROR_NONE+19)
#define MSGBOX_ERROR_FAIL_RESTART								(MSGBOX_ERROR_NONE+20)
#define MSGBOX_ERROR_INVALID_ADDRESS							(MSGBOX_ERROR_NONE+21)
#define MSGBOX_ERROR_APP_INIT_FAILURE							(MSGBOX_ERROR_NONE+22)
#define MSGBOX_ERROR_CANNOT_LOAD_REGISTRY						(MSGBOX_ERROR_NONE+23)
#define MSGBOX_ERROR_REGISTRY_QUOTA_LIMIT						(MSGBOX_ERROR_NONE+24)
#define MSGBOX_ERROR_SYSTEM_SHUTDOWN							(MSGBOX_ERROR_NONE+25)
#define MSGBOX_ERROR_HIBERNATED									(MSGBOX_ERROR_NONE+26)
#define MSGBOX_ERROR_RESUME_HIBERNATION							(MSGBOX_ERROR_NONE+27)
#define MSGBOX_ERROR_WAKE_SYSTEM								(MSGBOX_ERROR_NONE+28)
#define MSGBOX_ERROR_BACKUP_REG_FAILED							(MSGBOX_ERROR_NONE+29)
#define MSGBOX_ERROR_LOAD_CFG_FAILED							(MSGBOX_ERROR_NONE+30)
#define MSGBOX_ERROR_SAVE_CFG_FAILED							(MSGBOX_ERROR_NONE+31)
#define MSGBOX_ERROR_LOAD_SCHED_FAILED							(MSGBOX_ERROR_NONE+32)
#define MSGBOX_ERROR_SAVE_SCHED_FAILED							(MSGBOX_ERROR_NONE+33)
#define MSGBOX_ERROR_LOAD_HKEYSET_FAILED						(MSGBOX_ERROR_NONE+34)
#define MSGBOX_ERROR_SAVE_HKEYSET_FAILED						(MSGBOX_ERROR_NONE+35)
#define MSGBOX_ERROR_LOAD_PWRRMD_FAILED							(MSGBOX_ERROR_NONE+36)
#define MSGBOX_ERROR_SAVE_PWRRMD_FAILED							(MSGBOX_ERROR_NONE+37)
#define MSGBOX_ERROR_WRITE_LOG_FAILED							(MSGBOX_ERROR_NONE+38)
#define MSGBOX_ERROR_OUTPUT_LOG_FAILED							(MSGBOX_ERROR_NONE+39)
#define MSGBOX_ERROR_UNKNOWN									(MSGBOX_ERROR_NONE+40)

//////////////////////////////////////////////////////////////////////////

#define ERROR_HELPDLG_NOHELPFILE								(RESOURCEID_SPECIAL+1)
#define ERROR_HELPDLG_NOCHANGELOGFILE							(RESOURCEID_SPECIAL+2)

#define DAYOFWEEK_TITLE_SUNDAY									(RESOURCEID_SPECIAL+3)
#define DAYOFWEEK_TITLE_MONDAY									(RESOURCEID_SPECIAL+4)
#define DAYOFWEEK_TITLE_TUESDAY									(RESOURCEID_SPECIAL+5)
#define DAYOFWEEK_TITLE_WEDNESDAY								(RESOURCEID_SPECIAL+6)
#define DAYOFWEEK_TITLE_THURSDAY								(RESOURCEID_SPECIAL+7)
#define DAYOFWEEK_TITLE_FRIDAY									(RESOURCEID_SPECIAL+8)
#define DAYOFWEEK_TITLE_SATURDAY								(RESOURCEID_SPECIAL+9)

#define HKEYSET_KEYSTROKES_NULL									(RESOURCEID_SPECIAL+10)
#define HKEYSET_EXISTED_ALT_F4									(RESOURCEID_SPECIAL+11)
#define HKEYSET_EXISTED_ALT_F8									(RESOURCEID_SPECIAL+12)
#define HKEYSET_EXISTED_CTRL_F3									(RESOURCEID_SPECIAL+13)
#define HKEYSET_EXISTED_CTRL_F4									(RESOURCEID_SPECIAL+14)
#define HKEYSET_EXISTED_CTRL_F5									(RESOURCEID_SPECIAL+15)
#define HKEYSET_EXISTED_CTRL_WIN_F4								(RESOURCEID_SPECIAL+16)

#define PWRRMD_MSGCONTENT_SAMPLE								(RESOURCEID_SPECIAL+17)
#define PWRRMD_EVENT_AT_SETTIME									(RESOURCEID_SPECIAL+18)
#define PWRRMD_EVENT_AT_APPSTARTUP								(RESOURCEID_SPECIAL+19)
#define PWRRMD_EVENT_AT_SYSWAKEUP								(RESOURCEID_SPECIAL+20)
#define PWRRMD_EVENT_AT_BFRPWRACTION							(RESOURCEID_SPECIAL+21)
#define PWRRMD_EVENT_AT_PWRACTIONWAKE							(RESOURCEID_SPECIAL+22)
#define PWRRMD_EVENT_AT_APPEXIT									(RESOURCEID_SPECIAL+23)
#define PWRRMD_STYLE_MESSAGEBOX									(RESOURCEID_SPECIAL+24)
#define PWRRMD_STYLE_DIALOG										(RESOURCEID_SPECIAL+25)
#define PWRRMD_REPEATSET_SNOOZEINTERVAL							(RESOURCEID_SPECIAL+26)
